### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by Calinou** [pr0g/cmake-examples#1]
A license should be added to this repository, so that users know their rights. See [Choose a License](https://choosealicense.com) for more information :slightly_smiling_face:

**Comment by onqtam** [comment]
I added it to this list without a license - so let me know if you add one:

https://github.com/onqtam/awesome-cmake

**Comment by pr0g** [comment]
Excellent point, sorry will add this evening!

**Comment by pr0g** [comment]
Excellent point, sorry will add this evening!

**Comment by pr0g** [comment]
LICENSE file added a80d8d8 - thank you for the reminder! 👍
