### ISSUE TITLE
find_package(bec) - what is it?

### ISSUE THREAD

**Issue by jamesroyer** [pr0g/cmake-examples#11]
In `examples/more/external-project-add/CMakeLists.txt` there is a reference to a `bec` package but I can't find it.

**Comment by pr0g** [comment]
Hey @jamesroyer,

Ah `bec` is short for `bitfield enum class` and it's a [separate repo](https://github.com/pr0g/bit-field-enum-class) of mine I pull in using `ExternalProject_Add` here: `examples/more/external-project-add/external/CMakeLists.txt`.

If you run go into the `examples/more/external-project-add/external/` folder and run `configure-and-build.sh/bat` first, then run the main application it should work.

Let me know if you have any other issues 👍

**Comment by pr0g** [comment]
Closing this issue as the question about `bec` has been addressed.
